### ISSUE TITLE
Compatibility with Node Graph Assistant

### ISSUE THREAD

**Issue by elamhut** [hugoattal/ElectronicNodes#37]
Hey man, sorry for the second issue on your other plugin :P 

While trying out Electronic Nodes alongside the absolutely amazing Node Graph Assistant I found some incompatibilities.

https://youtu.be/ia3JR2hNil0

For instance the auto-snap node and line recoloring do not work when Electronic Node is turned on. Could you add support for Node Graph Assistant? That's a really amazing must-have plugin for working with nodes.

**Comment by hugoattal** [comment]
Oh, yes, this as been already addressed: https://github.com/hugoattal/ElectronicNodes/wiki/FAQ#is-it-compatible-with-other-plugins-like-blueprint-assist-or-node-graph-assistant

There were one user that noticed it a long time ago (last year I guess? Maybe before?) that some functions of NGA would not work with Electronic Nodes.

The problem is that Electronic Nodes and NGA both inject some of their code in the same place. I contacted the author of NGA to know if it was possible for its feature to work in another place, but he didn't find a proper solution IIRC 🤔.

So, to solve it in Electronic Nodes:
- You must disable the hotpatch feature in the settings (disable the "Use Hot Patch" option) and restart the engine
- Then you can add a shortcut to master activate/deactivate Electronic Nodes
It's located under Edit/Editor Preferences/General/Keyboard Shortcuts
![image](https://user-images.githubusercontent.com/4563971/116227803-cfc7c780-a754-11eb-86e2-ec3f76d20965.png)

That way, when you need to use some Node Graph Assistant feature, you just have to press the shortcut to temporarily disable Electronic Nodes (it's instantaneously). Though, I'm only aware of the auto-snap feature to be incompatible and requiring this.

**Comment by elamhut** [comment]
Thanks for the reply. It's sad that both assets don't work 100% with one another. At least it's 99% compatible tho. For now I've only found the snap to not work properly as well, which is a shame since it's extremely useful. Oh well, I'll keep using both, nothing breaking here :)

As always, thanks for the help!

**Comment by hugoattal** [comment]
> It's sad that both assets don't work 100% with one another

Yes, but as far as I know, I can't do much about it 😞 ... I'll keep that in the back of my head if someday I have an idea on how to make them both work.

> As always, thanks for the help!

No problem, don't hesitate to write an issue if you come across any other problem 🙂 ! (hopefully it was the last one 😛)

**Comment by namrog84** [comment]
For those that have arrived here wishing they had both. I really really wanted that 1% missing feature (auto connect) in regular blueprints. 

I started to dig through both code bases a bit.  And have stumbled upon a solution.

Here is an example of it in action.  Notice I cycle thru 4 styles and the insert node on wire still works! 

https://youtu.be/8Q2o4zprDtg

It maintains the original 3 of NGA, but also now incorporates a 4th subway ribbon support of Electronic Nodes. 
It'd be easy to add the EN's manhattan as well. 

Since both are closed and purchased source I can't and won't share the code, but I will give some 'hints' for those that wish to try and do this.


Inside NGA's `FNGAGraphConnectionDrawingPolicyCommon` ctor I added some EN code `connectionDrawingPolicy = new FENConnectionDrawingPolicy`

Then inside NGA's `OverrideDrawConnection` it generally does a big if/else 
`if (!GetDefault<UNodeGraphAssistantConfig>()->WireStyleStraight)`  whcih I replaced with a custom enum similiar to EN's like
`if (GetDefault<UNodeGraphAssistantConfig>()->WireStyleEnum == ECustomNodeGraphAssistantWireStyle::Default)`
then in the main else of this big if 
youll encounter a `FSlateDrawElement::MakeLines` right before Params.pDrawBubbles.

I added a simple  

```
bManhattan = GetDefault<UNodeGraphAssistantConfig>()->WireStyleEnum == ECustomNodeGraphAssistantWireStyle::Manhattan;
		if(bManhattan) {
			FSlateDrawElement::MakeLines
		}
		else {
			// electronic node area. subway lines
                        ...
			connectionDrawingPolicy->DrawConnection(LayerId, Start, End, params);
		}
```

The electronic node area here then falls over to the electronic nodes connecting drawing policy.

I had to make a variety of small changes to both plugins and for now I've merged them into 1 locally for the time being. But I think it might be possible to have them live side by side and fetch an 'externally registered connectionDrawingPolicy' here from NGA, that EN can register too and maintain both full plugin functionality. 


There are some limitations still, but I do think it'd be possible to find a way to make them both work. Else people can follow my above vague hints. 

If I can find a better solution and/or if both plugin authors were interested in accepting some potential PullRequests to their private repos, I'd be glad to do the work. 



p.s.  Just to reiterate, since both are closed source plugins that require purchase, I can't and won't share my shitty code, but I would be glad to talk with people about it. I am frequently around on unreal slackers discord namrog84#0880 if anyone does.
