### ISSUE TITLE
Electronic Node in Reference Viewer

### ISSUE THREAD

**Issue by lucastucious** [hugoattal/ElectronicNodes#45]
Is it possible to have straight lines in reference viewer ?

**Comment by hugoattal** [comment]
Hum, it should be possible with the new HotPatch feature! Btw I could also add SoundCue I think 🤔...

Will take a look this week 😉

**Comment by hugoattal** [comment]
Sorry for the delay...

It will be available in the next 3.4 update!
![image](https://user-images.githubusercontent.com/4563971/127018447-dd01f019-1953-4ac2-aa4d-3322a547d48c.png)

**Warning**: you'll need to activate HotPatch in the settings, since it will be disabled by default starting 3.4 (cf https://github.com/hugoattal/ElectronicNodes/issues/47)
